name: EC2 DevOps Setup Pipeline

# Trigger manually
on:
  workflow_dispatch:

jobs:
  setup-ec2:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo (optional, if you need repo content)
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Prepare SSH key for EC2
      - name: Prepare SSH Key
        run: |
          mkdir -p ~/.ssh
          # Write private key from GitHub Secrets
          echo "${{ secrets.BASTION_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/bastion.pem
          chmod 600 ~/.ssh/bastion.pem
          # Add EC2 host to known_hosts to avoid SSH prompt
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

      # 3️⃣ Connect to EC2 and install tools
      - name: Connect to EC2 and Install Tools
        run: |
          ssh -i ~/.ssh/bastion.pem \
              -o StrictHostKeyChecking=yes \
              -o UserKnownHostsFile=~/.ssh/known_hosts \
              ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} 'bash -s' <<'REMOTE'

          set -euo pipefail   # Exit on error, unset variable, or pipe failure

          echo "=== Step 1: Update packages ==="
          sudo apt-get update -y
          sudo apt-get install -y curl unzip jq git

          echo "=== Step 2: Install AWS CLI ==="
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

          echo "=== Step 3: Install kubectl ==="
          # Get latest stable Kubernetes version, remove newline
          KVER=$(curl -s https://dl.k8s.io/release/stable.txt | tr -d '\n')
          curl -LO "https://dl.k8s.io/release/${KVER}/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

          echo "=== Step 4: Install Helm ==="
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

          echo "=== Step 5: Install NGINX Ingress Controller ==="
          kubectl create namespace ingress-nginx || true
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx -n ingress-nginx || true

          echo "=== Step 6: Install ArgoCD ==="
          kubectl create namespace argocd || true
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

          echo "=== Step 7: Install Prometheus + Grafana ==="
          kubectl create namespace monitoring || true
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install kube-stack prometheus-community/kube-prometheus-stack -n monitoring || true

          echo "=== Step 8: Verify installation ==="
          echo "Pods in ArgoCD namespace:"
          kubectl get pods -n argocd
          echo "Pods in monitoring namespace:"
          kubectl get pods -n monitoring
          echo "Pods in ingress-nginx namespace:"
          kubectl get pods -n ingress-nginx

          echo "=== Installation Complete ==="
          REMOTE
